spring.application.name=patient-service
server.port=4000 

# Database configuration
#spring.datasource.url=jdbc:postgresql://localhost:5000/db?options=-c%20timezone=Asia/Yangon
#spring.datasource.username=admin_user
#spring.datasource.password=password
## Driver ကို အတိအကျ ထည့်ပေးပါ
#spring.datasource.driver-class-name=org.postgresql.Driver
#
## JPA / Hibernate configuration
#spring.jpa.hibernate.ddl-auto=update
##spring.sql.init.mode=always
## Postgres သုံးနေမှန်း သိအောင် dialect ထည့်ပေးပါ
#spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
#spring.jpa.show-sql=true
#
#
## Color & Logging
#spring.output.ansi.enabled=ALWAYS
#logging.pattern.console=%clr(%d{yyyy-MM-dd HH:mm:ss}){blue} %clr(%5p) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}
#
## For Swagger & Scalar UI
#springdoc.swagger-ui.path=/swagger-ui.html
#springdoc.api-docs.path=/v3/api-docs
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.ByteArraySerializer
logging.level.root=INFO