server:
  port: 4004

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        # --- Patient Service Route ---
        - id: patient-service-route
          uri: http://patient-service:4000
          predicates:
            - Path=/api/patients/**
          filters:
            - JwtValidation
            - StripPrefix=1

        # --- API Docs (Swagger) Route ---
        - id: api-docs-patient-route
          uri: http://patient-service:4000
          predicates:
            - Path=/api-docs/patients
          filters:
            - RewritePath=/api-docs/patients, /v3/api-docs

        # --- API Docs (Swagger) Route ---
        - id: api-docs-auth-route
          uri: http://auth-service:4005
          predicates:
            - Path=/api-docs/auth
          filters:
            - RewritePath=/api-docs/auth, /v3/api-docs
        # --- Auth Service Route ---
        - id: auth-service-route
          uri: http://auth-service:4005
          predicates:
            - Path=/auth/**

# Logging Configuration
logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.http.server.reactive: DEBUG
    org.springframework.web.reactive: DEBUG