syntax = "proto3";

// Java class တွေအတွက် package (သင့် Project structure နဲ့ ကိုက်ညီအောင် ပြင်နိုင်သည်)
option java_package = "com.pm.billing.grpc";
option java_multiple_files = true;

// Proto package name
package billing;

// Billing Service Definition
service BillingService {
  // RPC method definition
  rpc CreateBillingAccount(BillingRequest) returns (BillingResponse);
}

// Request Message
message BillingRequest {
  string patient_id = 1;
  string name = 2;
  string email = 3;
}

// Response Message
message BillingResponse {
  string account_id = 1;
  string status = 2;
  string message = 3;
}